name: Eleventy Build
on: [push]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - run: npm ci
        - run: npm run build
        - name: Deploy
          uses: peaceiris/actions-gh-pages@v3
          with:
            deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
            publish_dir: ./_site